CREATE TABLE B02DokKontrak (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    IdKode VARCHAR(20),
    IdKodeA04 VARCHAR(20),
    NoRegDok VARCHAR(50) NOT NULL,
    KategoriDok VARCHAR(50) NOT NULL,
    JenisDok VARCHAR(50) NOT NULL,
    KetDok VARCHAR(255),
    ValidasiDok VARCHAR(20) NOT NULL,
    TglTerbitDok DATE NOT NULL,
    TglBerakhirDok DATE NOT NULL,
    MasaBerlaku VARCHAR(100),
    TglPengingat DATE,
    MasaPengingat VARCHAR(100),
    FileDok VARCHAR(255) NOT NULL,
    StatusDok VARCHAR(20) NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at VARCHAR(50),
    updated_at VARCHAR(50),
    FOREIGN KEY (IdKodeA04) REFERENCES A04DmKaryawan(IdKode),
    FOREIGN KEY (created_by) REFERENCES A01DmUser(IdKode),
    FOREIGN KEY (updated_by) REFERENCES A01DmUser(IdKode)
);

CREATE TABLE B03DokKarir (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    IdKode VARCHAR(20),
    IdKodeA04 VARCHAR(20),
    NoRegDok VARCHAR(50) NOT NULL,
    KategoriDok VARCHAR(50) NOT NULL,
    JenisDok VARCHAR(50) NOT NULL,
    KetDok VARCHAR(255),
    ValidasiDok VARCHAR(20) NOT NULL,
    TglTerbitDok DATE NOT NULL,
    TglBerakhirDok DATE NOT NULL,
    MasaBerlaku VARCHAR(100),
    TglPengingat DATE,
    MasaPengingat VARCHAR(100),
    FileDok VARCHAR(255) NOT NULL,
    StatusDok VARCHAR(20) NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at VARCHAR(50),
    updated_at VARCHAR(50),
    FOREIGN KEY (IdKodeA04) REFERENCES A04DmKaryawan(IdKode),
    FOREIGN KEY (created_by) REFERENCES A01DmUser(IdKode),
    FOREIGN KEY (updated_by) REFERENCES A01DmUser(IdKode)
);

CREATE TABLE B04DokLegalitas (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    IdKode VARCHAR(20),
    IdKodeA04 VARCHAR(20),
    NoRegDok VARCHAR(50) NOT NULL,
    KategoriDok VARCHAR(50) NOT NULL,
    JenisDok VARCHAR(50) NOT NULL,
    KetDok VARCHAR(255),
    ValidasiDok VARCHAR(20) NOT NULL,
    TglTerbitDok DATE NOT NULL,
    TglBerakhirDok DATE NOT NULL,
    MasaBerlaku VARCHAR(100),
    TglPengingat DATE,
    MasaPengingat VARCHAR(100),
    FileDok VARCHAR(255) NOT NULL,
    StatusDok VARCHAR(20) NOT NULL,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at VARCHAR(50),
    updated_at VARCHAR(50),
    FOREIGN KEY (IdKodeA04) REFERENCES A04DmKaryawan(IdKode),
    FOREIGN KEY (created_by) REFERENCES A01DmUser(IdKode),
    FOREIGN KEY (updated_by) REFERENCES A01DmUser(IdKode)
);